### ISSUE TITLE
map_WKT

### ISSUE THREAD

**Issue by RobLBaker** [nationalparkservice/QCkit#33]
@juddpatterson is QCkit the best home for the `map_WKT()` function, or would it be a better fit in NPSutils? 

As a third alternative, we have an "NPStyles" package on the conceptual horizon that would have a lot of data viz templates (basic ggplot, etc function) with a common and consistent NPS style that is 508 compliant.

See the https://github.com/orgs/nationalparkservice/projects/3?pane=issue&itemId=18477474 for a proposed overview of package composition.

**Comment by juddpatterson** [comment]
I started this function thinking it would be useful for QC (both for plotting coordinates and confirming that the WKT was produced correctly), but now I hope that it does have broader utility. Without too much trouble it could be enhanced to support lines as well. NPSUtils sounds like a good match for now.

**Comment by RobLBaker** [comment]
Ok, I'll give it a day or so to make sure you're happy with it and then move it over.
