### ISSUE TITLE
Decrease margins of word document?

### ISSUE THREAD

**Issue by sarahkelso** [nationalparkservice/QCkit#94]
The tables print more nicely when the margins are 1" top, 1" bottom, and 0.75" on each side. Is it possible to adjust this in the code?

**Comment by RobLBaker** [comment]
I don't think this really matters. The .docx isn't the final product. The purpose of generating the .docx is so that authors can focus on content and not formatting. When the publications team converts the .docx to html/pdf/whatever, they will apply the necessary formatting including margins.
